// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnzrYA8Alngg0vGxyxQ2MxsWOaOiRjBMc',
    appId: '1:194121667871:web:1a0cbaf23a65507d7d4c2a',
    messagingSenderId: '194121667871',
    projectId: 'chat-app-43e00',
    authDomain: 'chat-app-43e00.firebaseapp.com',
    storageBucket: 'chat-app-43e00.firebasestorage.app',
    measurementId: 'G-S8G5L20K81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGuVvdKyJrylIzzd7Y7z86OSYXkQ0H_lU',
    appId: '1:194121667871:android:cea1a3bce15af6d27d4c2a',
    messagingSenderId: '194121667871',
    projectId: 'chat-app-43e00',
    storageBucket: 'chat-app-43e00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6okujYp6ZdzidVjQOrWOyNcaa9-2OXk',
    appId: '1:194121667871:ios:8703514d6e5f7ef47d4c2a',
    messagingSenderId: '194121667871',
    projectId: 'chat-app-43e00',
    storageBucket: 'chat-app-43e00.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ6okujYp6ZdzidVjQOrWOyNcaa9-2OXk',
    appId: '1:194121667871:ios:8703514d6e5f7ef47d4c2a',
    messagingSenderId: '194121667871',
    projectId: 'chat-app-43e00',
    storageBucket: 'chat-app-43e00.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnzrYA8Alngg0vGxyxQ2MxsWOaOiRjBMc',
    appId: '1:194121667871:web:621df2e567e6804a7d4c2a',
    messagingSenderId: '194121667871',
    projectId: 'chat-app-43e00',
    authDomain: 'chat-app-43e00.firebaseapp.com',
    storageBucket: 'chat-app-43e00.firebasestorage.app',
    measurementId: 'G-H9TG35ET5L',
  );
}
